name: Compile Sketches

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:nano"
          sketch-paths: |
            - ./Code/MainDisplay
            - ./Code/Controller
            - ./Code/Shotclock
          libraries: |
            - name: FastLED
            - name: RF24
            - name: SmartButton Library
            - source-path: ./Code/common
