name: Compile sketches
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main ]

# Where will they run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:nano"
          libraries:
      	    - name: FastLED
      	    - name: RF24
          sketch-paths:
            - Code/strip_test
